### ISSUE TITLE
为什么运行显示结果存在？感谢

### ISSUE THREAD

**Issue by ZZtac** [ox01024/Xray_Rad_Fusion#3]
file 2020-11-26/21:51:36 already exists, please backup and remove it at first

**Comment by ox01024** [comment]
删除上一次扫描结果

**Comment by ox01024** [comment]
可能存在bug 代码很简单改一下就可以了  最近没有精力修复

**Comment by ox01024** [comment]
2020：11：29 修复上一版本 关于时间戳和关闭主程序却无法关闭xray的BUG

**Comment by ox01024** [comment]
给个star吧

**Comment by ZZtac** [comment]
给了。

**Comment by ZZtac** [comment]
给了，感谢
