### ISSUE TITLE
linux下使用遇到问题

### ISSUE THREAD

**Issue by Shellc0d** [ox01024/Xray_Rad_Fusion#5]
![image](https://user-images.githubusercontent.com/53160265/155966132-3f3b4a71-d3c1-4856-829f-933f00da899b.png)
这是什么问题呢

**Comment by Shellc0d** [comment]
> ![image](https://user-images.githubusercontent.com/53160265/155966132-3f3b4a71-d3c1-4856-829f-933f00da899b.png) 这是什么问题呢

已解决 
修改如下文件 vim /usr/bin/google-chrome 将 exec -a "$0" "$HERE/chrome" "$@" 改为 exec -a "$0" "$HERE/chrome" "$@" --user-data-dir --no-sandbox

**Comment by ox01024** [comment]
chrome 沙盒问题
